services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234Asd..
      POSTGRES_DB: productsdb
    ports:
      - "5433:5432" # host:container
    volumes:
      - data-postgres-production:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgresql
    ports:
      - "8089:8088" # host:container
    restart: always
    networks:
      - spring

volumes:
  data-postgres-production:

networks:
  spring:
